Repository peeratmac/game-time, pull requests merged in 2019-09, with the labels that each got.

#14 Update Round and Round-test with checkSolve() method
  src/Round.js
  test/Round-test.js
Labels: bug, mvp-requirement, testing

#18 Round branch
  src/Round.js
  test/Round-test.js
Labels: bug, testing

#20 Create function for Turn to access Wheel output. w…
  src/Turn.js
  test/Turn-test.js
  test/Wheel-test.js
Labels: help wanted, mvp-requirement, testing

#21 Refactor choosePuzzle method on Puzzle class to store puzzle value in newPuzzle.
  src/Puzzle.js
  test/Puzzle-test.js
  test/Wheel-test.js
Labels: bug, help wanted, mvp-requirement, testing

#22 Fix methods in round, wheel, turn, and puzzle to pass all tests
  src/Puzzle.js
  src/Round.js
  src/Turn.js
  src/Wheel.js
  test/Puzzle-test.js
  test/Round-test.js
  test/Turn-test.js
  test/Wheel-test.js
Labels: bug, mvp-requirement, testing

#23 Update Turn-test with randomizeWheelVal running twice
  test/Turn-test.js
Labels: mvp-requirement, testing

#26 Link HTML to new CSS sheet
  src/css/base.css
  src/css/base.css.map
  src/css/base.scss
  src/index.html
Labels: styling

#27 Refactor start game
  src/Game.js
  src/Player.js
  src/Round.js
  src/Turn.js
  src/domUpdates.js
  src/index.html
  src/index.js
  test/Round-test.js
  test/Turn-test.js
Labels: bug, mvp-requirement, testing

#28 Update and refactor Players class along with all the tests for Playr
  src/Player.js
  test/Players-test.js
Labels: mvp-requirement, testing

#31 Refactor Game and Puzzle a little to connect with …
  src/Game.js
  src/Puzzle.js
  src/index.js
Labels: enhancement, mvp-requirement

#32 Update tests and methods in Round which bring total of tests passing to 24/26
  src/Round.js
  src/Turn.js
  test/Round-test.js
  test/Turn-test.js
  test/sample-test.js
Labels: mvp-requirement, testing

#33 Fix issue with puzzle class not storing newPuzzle
  src/Puzzle.js
Labels: bug, mvp-requirement, testing

#34 Add a fix to tests (small fixes, spellings)
  src/Game.js
  src/Puzzle.js
  test/Game-test.js
Labels: bug, testing

#36 Add header element and link some fonts to document
  src/index.html
Labels: enhancement

#37 Game class refrac
  src/Game.js
  src/Player.js
  src/Round.js
  test/Game-test.js
  test/Player-test.js
  test/Round-test.js
Labels: bug, enhancement, mvp-requirement, testing

#38 Prep HTML for modals, link some color schemes to scss file
  src/css/base.scss
  src/index.html
Labels: mvp-requirement, styling

#40 Add dom interaction for player names/puzzle loading
  src/Game.js
  src/domUpdates.js
  src/index.html
  src/index.js
Labels: mvp-requirement

#39 Minor patch for index.js to get npm start to run properly.
  src/css/base.css
  src/css/base.css.map
  src/index.js
Labels: bug, mvp-requirement, testing

#41 Updating most recent CSS changes
  src/css/base.scss
  src/index.html
Labels: CSS

#43 Styling 2
  src/css/_variables.scss
  src/css/base.scss
  src/index.html
Labels: styling

#44 Make the modal shows up on page load to enter in 3 players name
  src/Wheel.js
  src/css/base.scss
  src/domUpdates.js
  src/index.html
  src/index.js
  test/Wheel-test.js
Labels: bug, enhancement, mvp-requirement, styling, testing

#49 Style game start modal
  src/css/base.scss
  src/index.html
Labels: styling

#50 Add HTML section for player name/scores/total money.
  .vscode/launch.json
  src/Game.js
  src/Player.js
  src/Round.js
  src/domUpdates.js
  src/index.html
  src/index.js
Labels: bug, help wanted, mvp-requirement

#60 Style new elements and make font-sizes and footer more responsive
  src/css/base.scss
  src/index.html
Labels: mvp-requirement, styling

#63 Styling on spinner board
  src/css/base.scss
  src/index.html
Labels: styling

#62 Game play - currentRoundMoney and totalMoney update correctly in the DOM and class data
  src/Game.js
  src/Puzzle.js
  src/Round.js
  src/domUpdates.js
  src/index.js
Labels: enhancement, mvp-requirement

#65 Add current player indicator and already used letters section. Styli…
  src/css/base.scss
  src/index.html
Labels: styling

#66 Users can now see letters they have already used display on the DOM
  src/Round.js
  src/domUpdates.js
  src/index.html
  src/index.js
Labels: enhancement, mvp-requirement

#67 Improve styling on used letters container and added a category displa…
  src/css/base.scss
  src/index.html
Labels: styling

#68 Add category section and add ability for users to know whose turn it is
  src/domUpdates.js
  src/index.html
  src/index.js
Labels: enhancement, mvp-requirement, styling

#61 Incorporate data fetching to app
  src/Wheel.js
  src/index.js
Labels: enhancement

#69 Player fields
  src/Game.js
  src/domUpdates.js
  src/index.js
Labels: bug, mvp-requirement, styling

#72 Add puzzle appension method on DOMupdates, create styling, and insert…
  src/css/base.scss
  src/domUpdates.js
  src/index.html
  src/index.js
Labels: enhancement, mvp-requirement, styling

#73 Wheel addition - bankrupt and lose a turn logic + update on the DOM with the values.
  src/index.js
Labels: bug, enhancement, mvp-requirement

#78 Buy vowel guess consonant
  src/domUpdates.js
  src/index.js
Labels: enhancement, mvp-requirement

#79 Unhide letters on correct Guess a Letter attempt. Some small styling …
  src/Round.js
  src/Turn.js
  src/css/base.scss
  src/domUpdates.js
  src/index.js
Labels: bug, enhancement, mvp-requirement, styling

#80 Fix game breaking issues in index
  src/index.js
Labels: bug

#82 Hot fix the game from merge issue earlier
  src/index.js
Labels: bug

#83 Fix where the total money for different players were updated for a different player earlier
  src/domUpdates.js
  src/index.js
Labels: bug

#84 Hot fix the total score to be accurate after each round of correct solution
  src/domUpdates.js
  src/index.js
Labels: bug

#89 Add screenshots and update readme file
  README.md
  screenshots/desktop-view-1.png
  screenshots/desktop-view-2.png
  screenshots/working-product-1.gif
  screenshots/working-product-2.gif
Labels: documentation

#96 Update Player-test.js file to cover new methods written for player round money and total money
  test/Player-test.js
Labels: testing
